config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Pages
  # home pages
  root 'home#dashboard_page'
  get 'home/question_paper_page', to: 'home#question_paper_page', as: 'home_question_paper_page'
  get 'home/question_paper_edit_page/:questionpaper_id', to: 'home#question_paper_edit_page', as: 'home_question_paper_edit_page'
  get 'settings/profile_page', to: 'settings#profile_page', as:'settings_profile_page'

  # General pages
  get 'general/landing_page', to: 'general#landing_page', as: 'general_landing_page'

  # Functions
  # home functions
  # questionpaper
  post 'home/create_question_paper', to: 'home#create_question_paper', as: 'home_create_question_paper'
  delete 'home/delete_question_paper/:questionpaper_id', to: 'home#delete_question_paper', as: 'home_delete_question_paper'
  get 'home/edit_name_question_paper/:questionpaper_id', to: 'home#edit_name_question_paper', as: 'home_edit_name_question_paper'
  put 'home/edit_name_question_paper_submit/:questionpaper_id', to: 'home#edit_name_question_paper_submit', as: 'home_edit_name_question_paper_submit'
  get 'home/home_page/right_pane/:right_pane_view', to: 'home#home_page_right_pane_view', as: 'home_page_right_pane_view'

  # question
  post 'home/create_question/:questionpaper_id', to: 'home#create_question', as: 'home_create_question'
  delete 'home/delete_question/:question_id', to: 'home#delete_question', as: 'home_delete_question'
  get 'home/question/right_pane/:question_id', to:'home#question_question_right_pane', as: 'home_question_question_right_pane'
  post 'home/question/change_marks_for_question/:question_id', to: 'home#change_marks_for_question', as: 'home_change_marks_for_question'
  post 'home/question/enter_the_question/:question_id', to:'home#enter_the_question', as: 'home_enter_the_question'
  post 'home/solution/enter_the_solution/:question_id', to:'home#enter_the_solution', as: 'home_enter_the_solution'
  post 'home/question/question_paper_settings/:questionpaper_id', to: 'home#question_paper_settings', as: 'home_question_paper_settings'
  post 'home/solution/add_new_option/:question_id', to: 'home#add_new_option', as: 'home_add_new_option'
  delete 'home/solution/delete_option/:option_id', to: 'home#delete_option', as: 'home_delete_option'
  get 'home/solution/edit_mcqs_option/:option_id', to: 'home#edit_mcqs_option', as: 'home_edit_mcqs_option'
  put 'home/solution/edit_mcqs_option_submit/:option_id', to: 'home#edit_mcqs_option_submit', as: 'home_edit_mcqs_option_submit'

  # settings functions
  # profile page
  get 'settings/profile_page/right_pane/:right_pane_view', to: 'settings#profile_page_right_pane_view', as: 'settings_profile_page_right_pane_view'
  get 'settings/profile_page/edit_profile_details', to: 'settings#edit_profile_details', as: 'settings_edit_profile_details'
  post 'settings/profile_page/profile_details_submit_form', to: 'settings#profile_details_submit_form', as: 'settings_profile_details_submit_form'
  get 'settings/profile_page/edit_profile_details_school_details', to: 'settings#edit_profile_details_school_details', as: 'settings_edit_profile_details_school_details'
  post 'settings/profile_page/profile_details_school_details_submit_form', to: 'settings#profile_details_school_details_submit_form', as: 'settings_profile_details_school_details_submit_form'
  
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	before_action :authenticate_user!

	# Pages

	def profile_page
		# Shows profile page where analytics, profile, settings aare there
	end

	# Functions

	def profile_page_right_pane_view
		# changes the right pane view - analytics, profile, settings 
		@right_pane_view = params[:right_pane_view]
		respond_to do |format|
		    format.js
	  	end
	end

	def edit_profile_details
		# link to show the form of editing profile details
		respond_to do |format|
		    format.js
	  	end
	end

	def profile_details_submit_form
		# Submits the profile details form to update user information
		custom_current_user_id = current_user.id
		custom_current_user = User.find(custom_current_user_id)
		custom_current_user.update(params.require(:profile_details_submit_form).permit(:first_name, :last_name))

		respond_to do |format|
		    format.js
	  	end
	end

	def edit_profile_details_school_details
		# link to show the form of editing school details
		respond_to do |format|
		    format.js
	  	end
	end

	def profile_details_school_details_submit_form
		# Submits the school details form to update user information
		school = School.find(current_user.school_id)
		school.update(params.require(:profile_details_school_details_submit_form).permit(:name, :address, :description, :phone))
		
		respond_to do |format|
		    format.js
	  	end
	end
end

app/views/settings/profile_page/_profile_page_left_pane.html.erb
<div class="left_pane glassmorphism_3">
	<div id="profile_page_left_pane_details_partial_id">
		<%= render 'settings/profile_page/profile_page_left_pane_details'%>
	</div>
		
	<div  class="divider mb-1">
	</div>

	<div class="list-group">
		<%= link_to 'Profile details', settings_profile_page_right_pane_view_path('profile'), class:'list-group-item list-group-item-action question_highlight', id: 'settings_profile_page_right_pane_view_link_profile_details', remote: true%>
		<%= link_to 'Personal analytics', settings_profile_page_right_pane_view_path('analytics'), class:'text-white list-group-item list-group-item-action', id: 'settings_profile_page_right_pane_view_link_analytics', remote: true%>
		<%= link_to 'Settings', settings_profile_page_right_pane_view_path('settings'), class:'text-white list-group-item list-group-item-action ', id: 'settings_profile_page_right_pane_view_link_settings', remote: true%>
	</div>


</div>

app/views/settings/profile_page/_profile_page_left_pane_details.html.erb
<% custom_current_user_id = current_user.id %>
<% custom_current_user = User.find(custom_current_user_id)%>

<div class="text-center">
	<%= image_tag('background_image.jpg', size: "150", class: 'rounded_image_profile_pic')%>
</div>

<div class="text-center">
	<div class="user_info ">
		<% user_name = custom_current_user.first_name.to_s + " "+ custom_current_user.last_name.to_s%>
		<h6><%= truncate(user_name, length: 25)%></h6>
		<em>Teacher at</em>
		<br>
		<em><%= truncate(School.find(current_user.school_id).name, length: 25) %></em>
	</div>
</div>

app/views/settings/profile_page/_profile_page_right_pane_analytics.html.erb
<div class="right_pane glassmorphism_4">
	hi
</div>

app/views/settings/profile_page/_profile_page_right_pane_profile_details.html.erb
<div class="right_pane glassmorphism_4">
	<!-- profile details -->
	<div id="profile_details_display_only_id" >
		<div class="profile_details_heading">
			<div class="row">
				<div class="col-11">
					User Details
				</div>
				<div class="col-1">
					<%= link_to 'Edit', settings_edit_profile_details_path, class: 'white_link',remote: true %>
				</div>
			</div>				
		</div>

		<div class="profile_details_body">
			<div id="profile_page_right_pane_profile_details_body_partial">
				<div class="row">
					<div class="col-9">

						<div class="row mb-1">
							<div class="col-2">
								Name:
							</div>
							<div class="col-10">
								<% user_name = current_user.first_name.to_s + " "+current_user.last_name.to_s%>
								<%= user_name%>
							</div>
						</div>
						<div class="row mb-1">
							<div class="col-2">
								Role:
							</div>
							<div class="col-10">
								Teacher
							</div>
						</div>					
						
					</div>
					<div class="col-3">
						pic
					</div>
				</div>
			</div>					
		</div>
	</div>

	<div id="profile_details_edit_only_id" class="hide">
		<div class="profile_details_heading">
			<div class="row">
				<div class="col-11">
					User Details
				</div>
			</div>				
		</div>

		<div class="profile_details_body">
			<%= form_with scope: :profile_details_submit_form, url: settings_profile_details_submit_form_path, method: :post, remote: true do |f|%>
				<div class="row">
					<div class="col-9">
						<div class="row">
							<div class=" col-6">
								First name:
							</div>
							<div class=" col-6">
								Last name:
							</div>
						</div>
						<div class="row">
							<div class=" col-6">
								<%= f.text_field :first_name, value: current_user.first_name ,class: 'form-control'%>
							</div>
							<div class=" col-6">
								<%= f.text_field :last_name, value: current_user.last_name ,class: 'form-control'%>
							</div>
						</div>
						<div class="row mt-2">
							<div class="col-10">
								
							</div>
							<div class="col-2 text-center">
								<%= f.submit 'Save', class: 'btn btn-info'%>
							</div>							
						</div>
					</div>
					<div class="col-3">
						pic
					</div>
				</div>	
			<%end%>	
		</div>
	</div>
	

	<!-- school details -->
	<div id="profile_details_school_details_display_only_id">
		<div class="profile_details_heading">
			<div class="row">
				<div class="col-11">
					School Details
				</div>
				<div class="col-1">
					<%= link_to 'Edit', settings_edit_profile_details_school_details_path, class: 'white_link',remote: true %>
				</div>
			</div>				
		</div>

		<div class="profile_details_body">
			<div class="row">
				<div class="col-9">

					<div class="row mb-1">
						<div class="col-2">
							Name:
						</div>
						<div class="col-10">
							<%= School.find(current_user.school_id).name%>
						</div>
					</div>
					<div class="row mb-1">
						<div class="col-2">
							Description:
						</div>
						<div class="col-10">
							<%= School.find(current_user.school_id).description %>
						</div>
					</div>
					<div class="row mb-1">
						<div class="col-2">
							Address:
						</div>
						<div class="col-10">
							<%= School.find(current_user.school_id).address %>
						</div>
					</div>
					<div class="row mb-1">
						<div class="col-2">
							Phone:
						</div>
						<div class="col-10">
							<%= School.find(current_user.school_id).phone %>
						</div>
					</div>

				</div>
				<div class="col-3">
					pic
				</div>
			</div>		
		</div>
	</div>

	<div id="profile_details_school_details_edit_only_id" class="hide">
		<div class="profile_details_heading">
			<div class="row">
				<div class="col-11">
					School Details
				</div>
			</div>				
		</div>

		<div class="profile_details_body">
			<%= form_with scope: :profile_details_school_details_submit_form, url: settings_profile_details_school_details_submit_form_path, method: :post, remote: true do |f|%>
				<div class="row">
					<div class="col-9">
						<div class="row mb-2">
							<div class=" col-2">
								Name :
							</div>
							<div class=" col-10">
								<%= f.text_field :name, value: School.find(current_user.school_id).name ,class: 'form-control'%>
							</div>
						</div>

						<div class="row mb-2">
							<div class=" col-2">
								Description:
							</div>
							<div class=" col-10">
								<%= f.text_area :description, value: School.find(current_user.school_id).description ,class: 'form-control'%>
							</div>
						</div>

						<div class="row mb-2">
							<div class=" col-2">
								Address:
							</div>
							<div class=" col-10">
								<%= f.text_area :address, value: School.find(current_user.school_id).address ,class: 'form-control'%>
							</div>
						</div>

						<div class="row mb-2">
							<div class=" col-2">
								Phone:
							</div>
							<div class=" col-10">
								<%= f.telephone_field :phone, value: School.find(current_user.school_id).phone ,class: 'form-control'%>
							</div>
						</div>

						<div class="row mt-2">
							<div class="col-10">
								
							</div>
							<div class="col-2 text-center">
								<%= f.submit 'Save', class: 'btn btn-info'%>
							</div>							
						</div>
					</div>
					<div class="col-3">
						pic
					</div>
				</div>	
			<%end%>	
		</div>
	</div>
	

</div>

app/views/settings/profile_page/_profile_page_right_pane_settings.html.erb
<div class="right_pane glassmorphism_4">
	settings
</div>