config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Pages
  # home pages
  root 'home#dashboard_page'
  get 'home/question_paper_page', to: 'home#question_paper_page', as: 'home_question_paper_page'
  get 'home/question_paper_edit_page/:questionpaper_id', to: 'home#question_paper_edit_page', as: 'home_question_paper_edit_page'
  get 'settings/profile_page', to: 'settings#profile_page', as:'settings_profile_page'

  # General pages
  get 'general/landing_page', to: 'general#landing_page', as: 'general_landing_page'

  # Functions
  # home functions
  # questionpaper
  post 'home/create_question_paper', to: 'home#create_question_paper', as: 'home_create_question_paper'
  delete 'home/delete_question_paper/:questionpaper_id', to: 'home#delete_question_paper', as: 'home_delete_question_paper'
  get 'home/edit_name_question_paper/:questionpaper_id', to: 'home#edit_name_question_paper', as: 'home_edit_name_question_paper'
  put 'home/edit_name_question_paper_submit/:questionpaper_id', to: 'home#edit_name_question_paper_submit', as: 'home_edit_name_question_paper_submit'
  get 'home/home_page/right_pane/:right_pane_view', to: 'home#home_page_right_pane_view', as: 'home_page_right_pane_view'

  # question
  post 'home/create_question/:questionpaper_id', to: 'home#create_question', as: 'home_create_question'
  delete 'home/delete_question/:question_id', to: 'home#delete_question', as: 'home_delete_question'
  get 'home/question/right_pane/:question_id', to:'home#question_question_right_pane', as: 'home_question_question_right_pane'
  post 'home/question/change_marks_for_question/:question_id', to: 'home#change_marks_for_question', as: 'home_change_marks_for_question'
  post 'home/question/enter_the_question/:question_id', to:'home#enter_the_question', as: 'home_enter_the_question'
  post 'home/solution/enter_the_solution/:question_id', to:'home#enter_the_solution', as: 'home_enter_the_solution'
  post 'home/question/question_paper_settings/:questionpaper_id', to: 'home#question_paper_settings', as: 'home_question_paper_settings'
  post 'home/solution/add_new_option/:question_id', to: 'home#add_new_option', as: 'home_add_new_option'
  delete 'home/solution/delete_option/:option_id', to: 'home#delete_option', as: 'home_delete_option'
  get 'home/solution/edit_mcqs_option/:option_id', to: 'home#edit_mcqs_option', as: 'home_edit_mcqs_option'
  put 'home/solution/edit_mcqs_option_submit/:option_id', to: 'home#edit_mcqs_option_submit', as: 'home_edit_mcqs_option_submit'

  # settings functions
  # profile page
  get 'settings/profile_page/right_pane/:right_pane_view', to: 'settings#profile_page_right_pane_view', as: 'settings_profile_page_right_pane_view'
  get 'settings/profile_page/edit_profile_details', to: 'settings#edit_profile_details', as: 'settings_edit_profile_details'
  post 'settings/profile_page/profile_details_submit_form', to: 'settings#profile_details_submit_form', as: 'settings_profile_details_submit_form'
  get 'settings/profile_page/edit_profile_details_school_details', to: 'settings#edit_profile_details_school_details', as: 'settings_edit_profile_details_school_details'
  post 'settings/profile_page/profile_details_school_details_submit_form', to: 'settings#profile_details_school_details_submit_form', as: 'settings_profile_details_school_details_submit_form'
  
end

app/models/questionpaper.rb
class Questionpaper < ApplicationRecord
	belongs_to :user
	has_many :questions, dependent: :destroy
	validates :name, presence: { message: 'should not be empty' }
	validates :name, uniqueness: { scope: :user_id , message: 'is already taken, give a unique name'}
	validates :default_marks, presence: {message: 'should not be empty'}
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!

	############# Pages ################

	def dashboard_page	
		# This the dashboard page. It varies according to the type of user.
		# If it is an admin, student, teacher.
		# It shows the interaction between different roles.	
	end

	def question_paper_page
		# This is question paper page. The list of question papers can be seen here.
		# One can create, edit, view, delete papers here.
		# It is available for teacher role.
		@number_of_questions_per_page = 7 #The number can be changed to view number of questions per page
		@pagination_questions = Questionpaper.where(user_id: current_user.id).paginate(page: params[:page], per_page: @number_of_questions_per_page)
	end

	def question_paper_edit_page
		# Page for editing question papers
		@questionpaper = Questionpaper.find(params[:questionpaper_id])
	end

	########## Functions ###########

	# questionpaper
	def create_question_paper
		# This posts the question paper into the table
		@questionpaper = Questionpaper.new(params.require(:create_question_paper).permit(:name, :default_marks).merge(user_id: current_user.id, number_of_questions: 0, total_marks: 0))

		if @questionpaper.save
			redirect_to home_question_paper_edit_page_path(@questionpaper.id)
		else
			respond_to do |format|
			    format.js
		  	end
		end			
	end

	def delete_question_paper
		# One can delete question papers
		@questionpaper = Questionpaper.find(params[:questionpaper_id])
		@questionpaper.destroy
		@number_of_questions_per_page = 7 #The number can be changed to view number of questions per page
		@pagination_questions = Questionpaper.where(user_id: current_user.id)
		
		respond_to do |format|
		    format.js
	  	end
	end

	def edit_name_question_paper
		# For changing the name into a editable form 
		@questionpaper = Questionpaper.find(params[:questionpaper_id])
		respond_to do |format|
		    format.js
	  	end
	end

	def edit_name_question_paper_submit
		# To submit the name and changing the form to text 
		@questionpaper = Questionpaper.find(params[:questionpaper_id])
		@questionpaper.update(params.require(:edit_name_question_paper_submit).permit(:name))
		
		respond_to do |format|
		    format.js
	  	end
	end

	# questions
	def create_question
		# To create a question
		# Changes the number of questions in question paper accordingly
		# Modifies the total marks accordingly
		@questionpaper = Questionpaper.find(params[:questionpaper_id])
		question_number = Question.where(questionpaper_id: @questionpaper.id).count + 1
		default_marks = @questionpaper.default_marks
		@question = Question.create(questionpaper_id: @questionpaper.id, question_number: question_number, marks: default_marks)
		@question_id = @question.id

		number_of_questions = @questionpaper.number_of_questions
		number_of_questions = number_of_questions + 1
		@questionpaper.update(number_of_questions: number_of_questions)

		total_marks = 0 
		for i in Question.where(questionpaper_id: @questionpaper.id)
			total_marks = total_marks + i.marks 
		end

		@questionpaper.update(total_marks: total_marks)

		respond_to do |format|
		    format.js
	  	end
	end

	def delete_question
		# delete question from the table
		# Changes the number of questions in question paper accordingly
		# Adjusts the question number such that they will be continuous.
		# Modifies the total marks accordingly

		@question = Question.find(params[:question_id])
		@questionpaper = Questionpaper.find(@question.questionpaper_id)
		@question_id = @question.id

		# fixing the continuous question number
		deleting_question_number = @question.question_number

		for i in Question.where(questionpaper_id: @questionpaper.id)
			if i.question_number > deleting_question_number
				new_question_number = i.question_number - 1
				i.update(question_number: new_question_number)
			end
		end

		# fixing number of questions
		number_of_questions = @questionpaper.number_of_questions
		number_of_questions = number_of_questions - 1
		@questionpaper.update(number_of_questions: number_of_questions)

		# deleting the question
		@question.destroy

		# fixing the total marks
		total_marks = 0 
		for i in Question.where(questionpaper_id: @questionpaper.id)
			total_marks = total_marks + i.marks 
		end

		@questionpaper.update(total_marks: total_marks)

		# ajax
		respond_to do |format|
		    format.js
	  	end
	end

	def question_question_right_pane
		# This changes the right pane view based on the question selected
		@question = Question.find(params[:question_id])
		@questionpaper = Questionpaper.find(@question.questionpaper_id)
		@question_id = @question.id

		respond_to do |format|
		    format.js
	  	end
	end

	def change_marks_for_question
		# This changes the marks for the individual question.
		# And accordingly the total marks also change

		@question = Question.find(params[:question_id])
		@questionpaper = Questionpaper.find(@question.questionpaper_id)
		@question_id = @question.id
		if @question.update(params.require(:change_marks_for_question).permit(:marks))
			@updated = true

			# fixing the total marks		
			@questionpaper = Questionpaper.find(@question.questionpaper_id)
			total_marks = 0 

			for i in Question.where(questionpaper_id: @questionpaper.id)
				total_marks = total_marks + i.marks 
			end
			@questionpaper.update(total_marks: total_marks)

		else
			@updated = false
		end	

		respond_to do |format|
		    format.js
	  	end
	end

	def enter_the_question
		# User can enter the question in a text area and it stores in database
		@question = Question.find(params[:question_id])
		@question.update(params.require(:enter_the_question).permit(:question))
	end

	def enter_the_solution
		# User can enter the solution in a text area and it stores in database
		@question = Question.find(params[:question_id])
		@question.update(params.require(:enter_the_solution).permit(:solution))
	end

	def question_paper_settings
		# Submitting for modifying the question paper settings like default marks.
		@questionpaper = Questionpaper.find(params[:questionpaper_id])
		if @questionpaper.update(params.require(:question_paper_settings).permit(:default_marks))
			@updated = true
		else
			@updated = false
		end		

		respond_to do |format|
		    format.js
	  	end
	end

	def home_page_right_pane_view
		# Changing the right pane view of the home page
		@right_pane_view = params[:right_pane_view]
		respond_to do |format|
		    format.js
	  	end
	end

	def add_new_option
		# Add a new option to the mcqs
		@question = Question.find(params[:question_id])
		@question_id = @question.id
		Option.create(option: "New option", answer: false, question_id: @question.id)

		respond_to do |format|
		    format.js
	  	end
	end

	def delete_option
		# Delete the selected option in the mcqs
		@option = Option.find(params[:option_id])
		@question_id = @option.question_id
		@option.destroy

		respond_to do |format|
		    format.js
	  	end
	end

	def edit_mcqs_option
		# Edit the content of the mcqs - getting the text field
		@option = Option.find(params[:option_id])
		@question_id = @option.question_id

		respond_to do |format|
		    format.js
	  	end
	end

	def edit_mcqs_option_submit
		# Submitting the edited mcq option - and closing the text field
		@option = Option.find(params[:option_id])
		@question_id = @option.question_id
		@option.update(params.require(:edit_mcqs_option_submit).permit(:option))

		respond_to do |format|
		    format.js
	  	end
	end
end

app/views/home/question_paper/_error_messages_for_modal.html.erb
<%if @questionpaper%>
	<% if @questionpaper.errors.full_messages.any? %>
		<div class="alert alert-danger mt-2">
			<% @questionpaper.errors.full_messages.each do |error_message| %>
				<%= error_message %>
				<br>
			<% end %>
		</div>	  
	<% end %>
<% end %>

<%if @question%>
	<% if @question.errors.full_messages.any? %>
		<div class="alert alert-danger mt-2">
			<% @question.errors.full_messages.each do |error_message| %>
				<%= error_message %> 
				<br>
			<% end %>
		</div>	  
	<% end %>
<% end %>

app/views/home/question_paper/_error_messages_for_modal_in_creating_question_papers.html.erb
<%if @questionpaper%>
	<% if @questionpaper.errors.full_messages.any? %>
		<div class="alert alert-danger mt-2">
			<% @questionpaper.errors.full_messages.each do |error_message| %>
				<%= error_message if @questionpaper.errors.full_messages.first == error_message %> <br />
			<% end %>
		</div>	  
	<% end %>
<% end %>

app/views/home/question_paper/_list_of_question_papers_pagination.html.erb
<div class="digg_pagination container" style="overflow-x: auto; overflow-y: hidden;">
	<%= will_paginate pagination_questions, inner_window: 2, outer_window: 1%>
</div>

app/views/home/question_paper/_list_of_question_papers_table.html.erb
<table class="table table-striped gradient_background glassmorphism text-white mb-0">

  <thead>
    <tr>
      <th scope="col">S.no</th>
      <th scope="col">
        <span id="list_of_questions_table_colomn_name_attribute">Name</span>
      </th>
      <th scope="col">
        <span id="list_of_questions_table_colomn_class_attribute">Class</span>
      </th>
      <th scope="col">
        <span id="list_of_questions_table_colomn_no_of_questions_attribute">No: of Questions</span> 
      </th>
      <th scope="col">
        <span id="list_of_questions_table_colomn_marks_attribute"> Marks</span>
      </th>
      <th scope="col">
        <span id="list_of_questions_table_colomn_date_created_attribute" class="underline">Date Created</span> 
      </th>
      <th scope="col">Options</th>
    </tr>
  </thead>

  <tbody>
    <% count = 0%>
    <% for i in pagination_questions%>
      <% count = (count + 1)%>
      <tr>
        <th scope="row">
          <%if (count + number_of_questions_per_page*(params[:page].to_i - 1)) > number_of_questions_per_page%>
            <%= (count + number_of_questions_per_page*(params[:page].to_i - 1)) %>
          <%else%>
            <%= count %>
          <%end%>
        </th>
        <td><%= truncate(i.name, length: 25) %></td>
        <td></td>
        <td><%= i.number_of_questions %></td>
        <td><%= i.total_marks %></td>
        <td><%= i.created_at.to_date.to_formatted_s(:rfc822) %></td>
        <td> 
          <%= link_to '<i class="bi bi-pencil ml-3"></i>'.html_safe, home_question_paper_edit_page_path(i.id) %>

          <%= link_to '<i class="bi bi-trash ml-3"></i>'.html_safe, home_delete_question_paper_path(i.id), method: :delete, remote: true, data: { confirm: "Are you sure that you want to delete this question paper? "} %> 
            
        </td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/home/question_paper/_mcqs_partial.html.erb
<div class="mcq_box" >
	<div class="row options_for_the_question_header">
		<bold >Options</bold>
		Randomize options - checkbox

		<div class="dropdown" style="margin-left: auto; margin-right: 0;">
		  <button class="btn btn-info dropdown-toggle pl-5 pr-5" type="button" id="Question type" data-toggle="dropdown" aria-expanded="false">
		    Question type
		  </button>
		  <div class="dropdown-menu" aria-labelledby="Question type">
		  	<%= link_to "Descriptive", root_path, class: "dropdown-item" %> 
		  	<%= link_to "Multiple choice question", root_path, class: "dropdown-item" %> 
		  	<%= link_to "More than one answer", root_path, class: "dropdown-item" %> 
		  </div>
		</div>
	</div>

	<div >
		<table class="mt-1 mb-1 table table-bordered table-hover">
			<tbody>
				<% for i in Option.where(question_id: question_id)%>
					<% edit_mcqs_option_before = "edit_mcqs_option_before_" + i.id.to_s %>
					<% edit_mcqs_option_after = "edit_mcqs_option_after_" + i.id.to_s %>
					<% edit_mcqs_option_icons = "edit_mcqs_option_icons_" + i.id.to_s %>
					<tr>
						<td style="width:90%; padding: 0;" class="for_hover_delete_icon"> 
							<div class="row">
								<div class="col-10 option_padding" id= <%= edit_mcqs_option_before %>>
									<%= truncate(i.option, length: 35) %>
								</div>
								<div class="col-12 hide" id= <%= edit_mcqs_option_after %> >
						            <%= form_with scope: :edit_mcqs_option_submit, url: home_edit_mcqs_option_submit_path(i.id), method: :put, remote: true do |f|%>
						                <%= f.text_field :option, class: 'form-control', value: i.option %>
						            <%end%>
						        </div>
						        
								<div class="col-2" style="padding: 0; text-align: center;" id= <%= edit_mcqs_option_icons %> >
									<%= link_to '<i class="bi bi-pen hover_show"></i>'.html_safe, home_edit_mcqs_option_path(i.id), class: "option_edit_pen", method: :get, remote: true %>
									<%= link_to '<i class="bi bi-x hover_show"></i>'.html_safe, home_delete_option_path(i.id), class: "big-x", method: :delete, remote: true %>
								</div>
							</div>						
						</td>
						<td style="padding-bottom: 0;"><input class="" type="radio" name="exampleRadios"  value="option1" checked></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<%= link_to 'Add new option', home_add_new_option_path(@question_id), class: "add_new_option", method: :post, remote: true %>
	</div>		
</div>	

app/views/home/question_paper/_modal_for_creating_question_paper.html.erb
<!-- Button trigger modal -->

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Create new Question Paper
</button>


  <!-- Modal -->
<%= form_with scope: :create_question_paper, url: home_create_question_paper_path, method: :post, remote: true do |f|%>
  <div class="modal fade" id="exampleModal" data-backdrop="static" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Question Paper details</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="create_question_paper_close_icon">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

          <div class="row mb-2">
            <div class="col-4">
              Name <span style="color: red"> * </span> :
            </div>
            <div class="col-8">
              <%= f.text_field :name, class: 'form-control' %>
            </div>              
          </div>  

          <div class="row">
            <div class="col-4">
              Default marks <span style="color: red"> * </span> :
            </div>
            <div class="col-8 mb-2">
              <%= f.number_field :default_marks, step: 0.125 , min: 0, class: 'form-control', value: 2 %>
            </div>
          </div>

          <div id="create_question_paper_error_messages" >
            <%= render 'home/question_paper/error_messages_for_modal'%>
          </div>

        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->

          <%= f.submit 'Create', class: 'btn btn-primary'%>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/home/question_paper/_question_paper_edit_page_left_pane.html.erb
<% edit_name_before = "edit_name_before_" + @questionpaper.id.to_s %>
<% edit_name_after = "edit_name_after_" + @questionpaper.id.to_s %>
<% edit_name_icon = "edit_name_icon_" + @questionpaper.id.to_s %>

<div class="left_pane glassmorphism_3">

    <div class="list-group left_pane_questions">
      <li class="list-group-item glassmorphism_4 text-white p-2">
        <div class="row">
          <div class="col-10" id= <%= edit_name_before %> >
            <%=truncate(@questionpaper.name, length: 25) %>
          </div>
          <div class="col-12 hide" id= <%= edit_name_after%> >
            <%= form_with scope: :edit_name_question_paper_submit, url: home_edit_name_question_paper_submit_path(@questionpaper.id), method: :put, remote: true do |f|%>
              <%= f.text_field :name, class: 'form-control', value: @questionpaper.name %>
            <%end%>
          </div>
          <div class="col-2">
            <%= link_to '<i class="bi bi-pen"></i>'.html_safe, home_edit_name_question_paper_path(@questionpaper.id), class: 'text-white', id: edit_name_icon , remote: true %>
          </div>
        </div>      
      </li>

      <li class="list-group-item glassmorphism_4 text-white p-2">
        <div class="row">
          <div class="col-10">
            <span class="badge bg-primary rounded-pill" style="float: left;">
              <%= @questionpaper.total_marks %> marks
            </span>
          </div>
          <div class="col-2">
            <i class="bi bi-gear hover_pointer" data-toggle="modal" data-target="#exampleModal"></i>
          </div>
        </div>      
      </li>

      <!-- Settings icon Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <%= form_with scope: :question_paper_settings, url: home_question_paper_settings_path(@questionpaper.id), method: :post, remote: true do |f|%>
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Question paper settings</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="question_paper_settings_modal_close_button">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>

              <div class="modal-body">
                  <div class="row mb-3">
                    <div class="col-4">
                      Default marks <span style="color: red"> * </span> :
                    </div>
                    <div class="col-8">
                      <%= f.number_field :default_marks, step: 0.125 , min: 0, class: 'form-control', value: @questionpaper.default_marks %>
                    </div>
                  </div>  


                  <div id="question_paper_settings_error_messages" >
                    <%= render 'home/question_paper/error_messages_for_modal'%>
                  </div> 

              </div>

              <div class="modal-footer">
                <%= f.submit 'Save changes', class:'btn btn-primary'%>
              </div>
            </div>
          <%end%>
        </div>
      </div>

      <!-- question list -->

      <% question_count = 0 %>
      <% for i in Question.where(questionpaper_id: @questionpaper.id)%>
        <% question_count = question_count + 1 %>
        
        <% question_div_link = "question_div_link_" + i.id.to_s%>
        <% question_div_link_original = "question_div_link_original_" + i.id.to_s%>
        <% entire_question_div = "entire_question_div_" + i.id.to_s%>
        
        <div class="list-group-item list-group-item-action p-0 for_hover_delete_icon" id= <%= entire_question_div %>>
          <div class="row">
            <div class="col-8 hover_pointer p-3" id= <%= question_div_link%>>
              <%= link_to i.question_number, home_question_question_right_pane_path(i.id), id: question_div_link_original, class: 'question_number_link pl-3', remote: true %>
            </div>
            
            <div class="col-2 pt-3 pb-3 pl-0 pr-0" style="text-align: center;">


              <% marks_modal_id_with_sign = "#" + "marks_modal_id_" + i.id.to_s %>
              <% marks_modal_id_without_sign = "marks_modal_id_" + i.id.to_s %>
              <% marks_modal_label = "marks_modal_label_" + i.id.to_s %>
              <% marks_modal_close_id = "marks_modal_close_id_" + i.id.to_s%>

              <!-- Button trigger modal -->
              <span type= "button" class="badge bg-secondary text-light rounded-pill hover_show" data-toggle="modal" data-target= <%= marks_modal_id_with_sign %>>
                <%= i.marks%>
              </span>

              <!-- Modal -->
              <%= form_with scope: :change_marks_for_question, url: home_change_marks_for_question_path(i.id), method: :post, remote: true do |f|%>

              <div class="modal fade" tabindex="-1" aria-labelledby="<%= marks_modal_label%>" aria-hidden="true" id= <%= marks_modal_id_without_sign %>>
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="<%= marks_modal_label %>">
                        Marks for question <%= i.question_number %>
                      </h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="<%= marks_modal_close_id %>">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <div class="row">
                        <div class="col-2 pt-1">
                          Marks
                        </div>
                        <div class="col-10">
                          <%= f.number_field :marks, step: 0.125 , min: 0, class: 'form-control', value: i.marks %>
                        </div>                        
                      </div>

                      <br>

                      <div id="change_marks_for_questions_error_messages" >
                        <%= render 'home/question_paper/error_messages_for_modal'%>
                      </div>

                      <div style="float: left;">
                        <ul style="text-align: left;">
                          <li>Enter only numbers</li>
                          <li>Decimal increment in 0.125</li>
                        </ul>
                      </div>
                      
                    </div>
                    <div class="modal-footer">
                      <%= f.submit 'Save changes', class: 'btn btn-primary'%>
                    </div>
                  </div>
                </div>
              </div>
              <%end%> 

            </div>

            <div class="col-1 pt-3 pb-3 pl-0 pr-0">
              <%= link_to '<i class="bi bi-trash hover_show"></i>'.html_safe, home_delete_question_path(i.id), method: :delete, remote: true, data: { confirm: "Are you sure that you want to delete question #{i.question_number}? "} %>
            </div>
          </div>        
        </div>

        <script type="text/javascript">
          document.getElementById('<%= question_div_link %>').onclick = function() {
            document.getElementById('<%= question_div_link_original %>').click();
          }
          <%if question_count == 1 %>
            document.getElementById('<%= entire_question_div %>').classList.add('question_highlight');
          <%end%>
        </script>
      <%end%>



      <%= link_to 'Add a new question', home_create_question_path(@questionpaper.id), class: "list-group-item list-group-item-action list-group-item-info mb-5", method: :post, remote: true %>
    </div>

    <div>
    	<button type="button" class="btn btn-info left_pane_submit_button" >Generate question paper</button>
    </div>

</div>

app/views/home/question_paper/_question_paper_edit_page_right_pane.html.erb
<% if question_id != 0 %>
<% question = Question.find(question_id)%>
	<div class="right_pane glassmorphism_3">
		<div class="row  question_row m-0">
			<div class="col-6 box_divider">
				<div class="row enter_the_question_row" >
					<%= form_with scope: :enter_the_question, url: home_enter_the_question_path(question_id), method: :post, class: 'enter_the_question_form' do |f|%>
							<%if question.question && question.question.length != 0%>	
								<%= f.text_area :question, class: 'text_area_for_entering_question', onchange: 'this.form.submit()', value: question.question %>
							<%else%>
								<%= f.text_area :question, class: 'text_area_for_entering_question', onchange: 'this.form.submit()', placeholder: 'Please type your question here.' %>
							<%end%>							
							<%= f.submit 'Save', class: 'hide' %>	
					<%end%>	
				</div>			
			</div>
			<div class="col-6 box_divider pl-3 pr-4 pt-1 pb-1">
				<div class="row variable_boxes">
					<%= render 'home/question_paper/question_variables_partial', question_id: question_id %>
				</div>
			</div>
		</div>

		<div class="row m-0 answer_row">
			<div class="col-6 box_divider">
				<div class="row enter_the_question_row" >
					<%= form_with scope: :enter_the_solution, url: home_enter_the_solution_path(question_id), method: :post, class: 'enter_the_question_form' do |f|%>
							<%if question.solution && question.solution.length != 0%>	
								<%= f.text_area :solution, class: 'text_area_for_entering_question', onchange: 'this.form.submit()', value: question.solution %>
							<%else%>
								<%= f.text_area :solution, class: 'text_area_for_entering_question', onchange: 'this.form.submit()', placeholder: 'Please enter your solution here.' %>
							<%end%>
							<%= f.submit 'Save', class: 'hide' %>	
					<%end%>	
				</div>
			</div>
			<div class="col-6 box_divider pl-3 pr-4 pt-1 pb-1">
				<div class="row variable_boxes">
					<%= render 'home/question_paper/solution_variables_partial', question_id: question_id %>
				</div>				
			</div>
		</div>	
	</div>

<%else%>
	<div class="right_pane">
		<div class="glassmorphism_5 no_list_of_questions">
			<h2> Add the questions to edit them</h2>
			<h5>Click on 'Add a new question' button on the left pane.</h5>
		</div>
	</div>	
<% end %>

app/views/home/question_paper/_question_variables_partial.html.erb
<%= question_id%>

<p style="color:white;">
  When \(a \ne 0\), there are two solutions to \(ax^2 + bx + c = 0\) and they are
  \[x = {-b \pm \sqrt{b^2-4ac} \over 2a}.\]
</p>

<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async
      src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script>