config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Pages
  # home pages
  root 'home#dashboard_page'
  get 'home/question_paper_page', to: 'home#question_paper_page', as: 'home_question_paper_page'
  get 'home/question_paper_edit_page/:questionpaper_id', to: 'home#question_paper_edit_page', as: 'home_question_paper_edit_page'
  get 'settings/profile_page', to: 'settings#profile_page', as:'settings_profile_page'

  # General pages
  get 'general/landing_page', to: 'general#landing_page', as: 'general_landing_page'

  # Functions
  # home functions
  # questionpaper
  post 'home/create_question_paper', to: 'home#create_question_paper', as: 'home_create_question_paper'
  delete 'home/delete_question_paper/:questionpaper_id', to: 'home#delete_question_paper', as: 'home_delete_question_paper'
  get 'home/edit_name_question_paper/:questionpaper_id', to: 'home#edit_name_question_paper', as: 'home_edit_name_question_paper'
  put 'home/edit_name_question_paper_submit/:questionpaper_id', to: 'home#edit_name_question_paper_submit', as: 'home_edit_name_question_paper_submit'
  get 'home/home_page/right_pane/:right_pane_view', to: 'home#home_page_right_pane_view', as: 'home_page_right_pane_view'

  # question
  post 'home/create_question/:questionpaper_id', to: 'home#create_question', as: 'home_create_question'
  delete 'home/delete_question/:question_id', to: 'home#delete_question', as: 'home_delete_question'
  get 'home/question/right_pane/:question_id', to:'home#question_question_right_pane', as: 'home_question_question_right_pane'
  post 'home/question/change_marks_for_question/:question_id', to: 'home#change_marks_for_question', as: 'home_change_marks_for_question'
  post 'home/question/enter_the_question/:question_id', to:'home#enter_the_question', as: 'home_enter_the_question'
  post 'home/solution/enter_the_solution/:question_id', to:'home#enter_the_solution', as: 'home_enter_the_solution'
  post 'home/question/question_paper_settings/:questionpaper_id', to: 'home#question_paper_settings', as: 'home_question_paper_settings'
  post 'home/solution/add_new_option/:question_id', to: 'home#add_new_option', as: 'home_add_new_option'
  delete 'home/solution/delete_option/:option_id', to: 'home#delete_option', as: 'home_delete_option'
  get 'home/solution/edit_mcqs_option/:option_id', to: 'home#edit_mcqs_option', as: 'home_edit_mcqs_option'
  put 'home/solution/edit_mcqs_option_submit/:option_id', to: 'home#edit_mcqs_option_submit', as: 'home_edit_mcqs_option_submit'

  # settings functions
  # profile page
  get 'settings/profile_page/right_pane/:right_pane_view', to: 'settings#profile_page_right_pane_view', as: 'settings_profile_page_right_pane_view'
  get 'settings/profile_page/edit_profile_details', to: 'settings#edit_profile_details', as: 'settings_edit_profile_details'
  post 'settings/profile_page/profile_details_submit_form', to: 'settings#profile_details_submit_form', as: 'settings_profile_details_submit_form'
  get 'settings/profile_page/edit_profile_details_school_details', to: 'settings#edit_profile_details_school_details', as: 'settings_edit_profile_details_school_details'
  post 'settings/profile_page/profile_details_school_details_submit_form', to: 'settings#profile_details_school_details_submit_form', as: 'settings_profile_details_school_details_submit_form'
  
end

app/views/layouts/_login_messages.html.erb
<% if notice %>
  <div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    <%= alert %>
  </div>
<% end %> 

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-info" >
  <div class="container-fluid">
    
    <%= link_to general_landing_page_path, class: 'navbar-brand' do %>
      <%= image_tag('brand_logo.png', size: "25", class: "d-inline-block align-top")%>
      A&Q
    <%end%> 

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <li class="nav-item">
         <%= link_to 'Home', root_path, class: 'nav-link active',id: 'dashboard_navbar' %>
        </li>
        <li class="nav-item">
         <%= link_to 'Question Papers', home_question_paper_page_path, class: 'nav-link',  id: 'question_papers_navbar'%>
        </li>
        <li class="nav-item">
         <%= link_to 'Profile', settings_profile_page_path, class: 'nav-link',  id: 'profile_navbar'%>
        </li>
        
      </ul>

      <span class="form-inline my-2 my-lg-0">
        <%= link_to 'Sign Out', destroy_user_session_path, class: 'text-white', method: :delete%>
      </span>

    </div>    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnswersAndQuestions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>